git clone https://github.com/scoute-dich/browser.git	FLOSS_Browser
hg clone https://hg.mozilla.org/mozilla-central	Firefox
git clone https://github.com/anthonycr/Lightning-Browser.git	Lightning_Browser
git clone https://github.com/midori-browser/midori-android.git	Midori_Browser
git clone https://github.com/darvin/zirco-browser.git	Zirco
git clone https://github.com/chromium/chromium.git	Chromium
git clone https://github.com/kiwibrowser/android.git	Kiwi_Browser
git clone https://github.com/powerpoint45/Lucid-Browser.git	Lucid_Browser
git clone https://github.com/MoonchildProductions/Pale-Moon.git	Pale_Moon
git clone https://github.com/JTechMe/JumpGo.git	JumpGo_Browser
git clone https://github.com/PhilippC/keepass2android.git	Keepass2Android
git clone https://github.com/arunkumar9t2/lynket-browser.git	Lynket_Browser
git clone https://operasoftware.github.io/upstreamtools/	Opera_com_VPN_gratuita
git clone https://git.stoutner.com/?p=PrivacyBrowser.git;a=summary	Privacy_Browser
git clone https://github.com/n8fr8/tor-android.git	Tor-Browser
git clone https://f-droid.org/en/packages/org.gnu.icecat/	IceCatMobile
git clone https://github.com/MrAlex94/Waterfox.git	Waterfox
git clone https://github.com/mozilla-mobile/focus-android	Firefox_Focus
git clone https://github.com/hazuki0x0/YuzuBrowser.git	Yuzu_Browser
git clone https://github.com/cliqz-oss/browser-android.git	Cliqz
git clone https://github.com/f-droid/fdroidclient.git	Fennec_F-Droid
git clone https://github.com/Eloston/ungoogled-chromium.git	Ungoogled_Chromium
hg clone https://hg.mozilla.org/mozilla-central/	Firefox_Nightly
git clone https://github.com/iridium-browser/iridium-browser-dev.git	Iridium_Browser
git clone https://github.com/kiwibrowser/android.git	Kiwi_Browser_-_Fast_&_Quiet
git clone https://github.com/guardianproject/Orfox.git	Orfox_Browser
git clone https://github.com/brave/browser-android-tabs.git	Brave
git clone https://github.com/anthonycr/Lightning-Browser.git	UFO_Web_Browser
git clone https://github.com/scoute-dich/browser.git	Smart_Browser
git clone https://github.com/duckduckgo/android	Ducky_Browser
